# Generated by Django 2.1 on 2018-09-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='color',
        ),
    ]
