# Generated by Django 2.1 on 2018-09-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='OtherImage',
        ),
    ]
