# Generated by Django 2.1 on 2018-09-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='music',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
