# Generated by Django 2.1 on 2018-09-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180920_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='music_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
