# Generated by Django 2.1 on 2018-10-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
