# Generated by Django 2.1 on 2018-09-30 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Witdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('referral_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=200)),
                ('read_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=200)),
                ('comment_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
