# Generated by Django 2.1 on 2018-09-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='witdraw',
            name='bank_account_name',
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='witdraw',
            name='bank_account_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
