# Generated by Django 2.1 on 2018-09-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witdrawals', '0002_auto_20180930_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='witdraw',
            name='witdrawals',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
