# Generated by Django 2.1 on 2018-09-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('witdrawals', '0003_witdraw_witdrawals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='witdraw',
            name='witdrawals',
        ),
    ]
