# Generated by Django 2.1 on 2018-09-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witdrawals', '0004_remove_witdraw_witdrawals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witdraw',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
