# Generated by Django 2.1 on 2018-10-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('witdrawals', '0005_auto_20180930_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='witdraw',
            options={'ordering': ['-date']},
        ),
    ]
