# Generated by Django 2.1 on 2018-09-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promote_instagram', models.CharField(max_length=120)),
                ('promote_twitter', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='site_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesettings.SiteSettings'),
        ),
    ]
