# Generated by Django 2.1 on 2018-09-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_auto_20180923_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='activate_witdrawal',
            field=models.BooleanField(default=True),
        ),
    ]
