# Generated by Django 2.1 on 2018-10-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_sitesettings_activate_witdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='site_settings',
        ),
        migrations.RemoveField(
            model_name='widrawal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='activate_witdrawal',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='promote_instagram',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='promote_twitter',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='advertise',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_us',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='withdraw',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='Widrawal',
        ),
    ]
