# Generated by Django 2.1 on 2018-09-24 20:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('firstname', models.CharField(max_length=120, verbose_name='first name')),
                ('lastname', models.CharField(max_length=120, verbose_name='last name')),
                ('cupon_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='cupon code')),
                ('referral_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=200)),
                ('read_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=200)),
                ('comment_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=200)),
                ('referral_code', models.CharField(max_length=10, verbose_name='referral code')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('read', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('comment_on_posts', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
