# Generated by Django 2.1 on 2018-09-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cuponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='read_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
    ]
