# Generated by Django 2.1 on 2018-09-20 17:34

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180915_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='read',
            field=models.CharField(blank=True, max_length=999999999999999999, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
