# Generated by Django 2.1 on 2018-09-22 07:32

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='read',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
