# Generated by Django 2.1 on 2018-09-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180922_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
    ]
