# Generated by Django 2.1 on 2018-09-24 12:16

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_on_posts',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
